[package]
name = "shutdown"
version = "0.1.0"
edition = "2021"

[lib]
path = "shutdown.rs"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tokio-util.workspace = true
monoio.workspace = true
ctrlc = "3.4.4"