[package]
name = "hasher"
version = "0.1.0"
edition = "2021"

[lib]
path = "hasher.rs"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tokio-util.workspace = true
fnv = "1.0.7"